# Generated by Django 5.1.6 on 2025-03-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='category',
            field=models.CharField(blank=True, choices=[('Pencil Drawing', 'Pencil Drawing'), ('Paintings', 'Paintings'), ('Thread_Art', 'Thread Art')], max_length=20),
        ),
    ]
