# Generated by Django 5.1.6 on 2025-03-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_customer_password_artwork_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='category',
            field=models.CharField(blank=True, choices=[('pencil', 'Pencil Drawing'), ('painting', 'Painting'), ('thread', 'Thread Art')], max_length=20),
        ),
    ]
